### ISSUE TITLE
Anti-Aliasing on Linux + i3-wm

### ISSUE THREAD

**Issue by Daaniiieel** [rxi/microui#25]
Basically it seems like anti-aliasing doesn't work well. Both on the browser demo and real microgui apps (lite editor). 
![DeepinScreenshot_lite_20200417170250](https://user-images.githubusercontent.com/41679054/79583563-8f5b5580-80cd-11ea-8883-11fed6d6409b.png)
![DeepinScreenshot_Navigator_20200417170320](https://user-images.githubusercontent.com/41679054/79583570-91251900-80cd-11ea-90f0-5aafe1687384.png)

**Comment by rxi** [comment]
The first screenshot is of a message box produced by SDL and doesn't involve `microui` (if you consider this an issue it's an issue with the SDL library). The second screenshot is expected behaviour at a non-integer scaling factor -- the demo doesn't aim to support a wide range of scaling factors, but instead show a concise example of how to use `microui`.

As `microui` is renderer agnostic, in a real project you're expected to bring your own rendering which may or may not handle the case of non-integer scaling factors better. Problems with the demo's text rendering at certain scaling factors isn't an issue with the library.
